import streamlit as st
import utils.design_format as format
import utils.utility as util
import pandas as pd

st.set_page_config(
    page_title="PowerText Analysis Platform",
    page_icon="🔥",
)

format.add_logo()

st.title("🔥PowerText Analysis System")
format.horizontal_line()
st.subheader("Welcome to PowerText!")
format.align_text("This is a demo of the PowerText Analysis System. The system is designed to help you analyse content retrieved from social media and automatically classify these posts into broad Terms-of-service violations.", "justify")
format.align_text(
    "For the purpose of this demo, will we upload a CSV of scraped data from Reddit.", "justify")
format.horizontal_line()

uploaded_file = st.file_uploader("Upload CSV file", type="csv")

if uploaded_file is not None:
    st.write("You selected `%s`" % uploaded_file.name)
    if st.button("Upload CSV"):
        # Storing CSV data to ST cache
        util.cache_object(pd.read_csv(uploaded_file), "csv_file")
        util.customDisppearingMsg(
            "PDF file uploaded successfully!", wait=3, type_='success', icon=None)
        util.customDisppearingMsg(
            "You may now navigate to the other tabs for analysis of the Reddit content!", wait=-1, type_='info', icon=None)

format.horizontal_line()


@st.cache_data
def convert_df(df):
    return df.to_csv(index=False).encode('utf-8')


deployed_on_st = True
if deployed_on_st:
    path = "analysis_system/"
else:
    path = ""

with st.expander("Download Sample CSVs for Demo"):
    st.subheader("For Demo Purposes Only:")

    # Download sample CSV for scraped data
    format.align_text(
        "The CSV file used for this demo can be downloaded from the link below:", "justify")

    demo_reddit = pd.read_csv(f"{path}data_store/scraped/reddit_content.csv")
    demo_reddit_dl = convert_df(demo_reddit)
    st.write("")
    st.download_button(
        label="Download Sample Reddit content as CSV",
        data=demo_reddit_dl,
        file_name="Reddit_Sample.csv",
        mime="text/csv",
    )

    # Download sample CSV for feedback data
    try:

        demo_feedback = pd.read_csv(f"{path}data_store/feedback/feedback.csv")
        format.align_text(
            "The feedback CSV file generated by the system can be downloaded from the link below:", "justify")

        demo_feedback_dl = convert_df(demo_feedback)
        st.write("")
        st.download_button(
            label="Download Sample Feedback CSV",
            data=demo_feedback_dl,
            file_name="Feedback_Sample.csv",
            mime="text/csv",
        )
    except:
        pass
